## Fitting the Parity Function

In this tutorial, we try to build a variational circuit that approximates the **parity fuction**:  
$$f: x \in \{0,1 \} ^{\otimes n} \rightarrow y = \begin{cases}
1 & \text{if uneven number of 1's in $x$}\\
0 & \text{else}
\end{cases}
$$

We encode the binary input values of $x$ as basis states at the initialization of the circuit. Since the encoded states are simply the computational basis states, this method is called **basis encoding**.

In [1]:
import pennylane as qml
from pennylane import numpy as np
from pennylane.optimize import NesterovMomentumOptimizer

In [2]:
# set up device
dev = qml.device("default.qubit")

A variational circuit is typically constructed with a series of **layers**. Each layer consists of parametrized rotation gates operated on each qubit, followed by a ring of CNOT gates that entangle each qubit with its neighbour.

In [3]:
def layer(layer_weights):
    for wire in range(4):
        qml.Rot(*layer_weights[wire], wires=wire)

    for wires in ([0, 1], [1, 2], [2, 3], [3, 0]):
        qml.CNOT(wires)

Prepare basis state $\Ket{x}$ using the `qml.BasisState()` function.

In [4]:
def state_preparation(x):
    qml.BasisState(x, wires=[0, 1, 2, 3])

Construct the circuit by first initializing the basis state, and then calling in parametrized layers. At the end, return the expected value of the Pauli operator $Z$ on the $0th$ qubit.

In [5]:
@qml.qnode(dev)
def circuit(weights, x):
    state_preparation(x)

    for layer_weights in weights:
        layer(layer_weights)

    return qml.expval(qml.PauliZ(0))

We add a "classical" bias to the expectation value obtained from the quantum circuit and return it. The circuit, along with the bias, is the variational classifier we wish to optimize. Given the binary input $x$, we want the variational classifier to return the value of the parity function.

In [6]:
def variational_classifier(weights, bias, x):
    return circuit(weights, x) + bias

Further, we define the accuracy metric and cost function. 

The cost function is defined as the mean of the square of the difference between the predicted values by the variational classifier and the target values (i.e., labels):
$$\text{Cost} = \dfrac{1}{n}\sum_{i=1}^{n}(\text{Prediction}(i) - \text{Label}(i))^2$$
The accuracy metric is defined as
$$\text{Acc} = \dfrac{1}{n}\sum_{i=1}^{n}\text{Bool}(\text{label}(i) - \text{prediction}(i)=0)$$
Allowing for small computational errors, we set the condition inside the `bool` function to be {$<10^{-5}$} instead of {$=0$}.

In [7]:
def square_loss(labels, predictions):
    # We use a call to qml.math.stack to allow subtracting the arrays directly
    return np.mean((labels - qml.math.stack(predictions)) ** 2)

In [8]:
def accuracy(labels, predictions):
    acc = sum(abs(l - p) < 1e-5 for l, p in zip(labels, predictions))
    acc = acc / len(labels)
    return acc

In [9]:
def cost(weights, bias, X, Y):
    predictions = [variational_classifier(weights, bias, x) for x in X]
    return square_loss(Y, predictions)

#### Optimization

Import data from `parity_train.txt` file and load it into `X` and `Y` arrays, shift `Y` labels from $\{0,1\}$ to $\{-1,1\}$, and print the function values.

In [10]:
# import data from parity_train.txt file and load it into X and Y arrays
data = np.loadtxt("variational_classifier/data/parity_train.txt", dtype=int)
X = np.array(data[:, :-1])
Y = np.array(data[:, -1])

# shift label from {0, 1} to {-1, 1}
Y = Y * 2 - 1

# print function values
for x,y in zip(X, Y):
    print(f"x = {x}, y = {y}")

x = [0 0 0 1], y = 1
x = [0 0 1 0], y = 1
x = [0 1 0 0], y = 1
x = [0 1 0 1], y = -1
x = [0 1 1 0], y = -1
x = [0 1 1 1], y = 1
x = [1 0 0 0], y = 1
x = [1 0 0 1], y = -1
x = [1 0 1 1], y = 1
x = [1 1 1 1], y = -1


The state $\Ket{x}$ is made of four binary digits, and thus we set the number of qubits to be four. We guess the number of layers sufficient to be two. We randomly initialize the weights and bias.

In [11]:
np.random.seed(0)
num_qubits = 4
num_layers = 2
weights_init = 0.01 * np.random.randn(num_layers, num_qubits, 3, requires_grad=True)
bias_init = np.array(0.0, requires_grad=True)

print("Weights:", weights_init)
print("Bias: ", bias_init)

Weights: [[[ 0.01764052  0.00400157  0.00978738]
  [ 0.02240893  0.01867558 -0.00977278]
  [ 0.00950088 -0.00151357 -0.00103219]
  [ 0.00410599  0.00144044  0.01454274]]

 [[ 0.00761038  0.00121675  0.00443863]
  [ 0.00333674  0.01494079 -0.00205158]
  [ 0.00313068 -0.00854096 -0.0255299 ]
  [ 0.00653619  0.00864436 -0.00742165]]]
Bias:  0.0


Define Optimizer and batch size \\
Nesterov Momentum Optimizer is a gradient-descent optimizer. The batch size helps with randomly selecting a limited number of data points to calculate cost and optimize over.

In [12]:
opt = NesterovMomentumOptimizer(0.5)
batch_size = 5

Train the model over a hundred iterations. At each iteration, a random batch of data points is selected. The cost function with the parameters of the iteration is calculated, and gradient descent is applied and the next iteration of parameters is thus found trying to minimize the cost.

In [13]:
weights = weights_init
bias = bias_init
for it in range(100):

    # Update the weights by one optimizer step, using only a limited batch of data
    batch_index = np.random.randint(0, len(X), (batch_size,))
    X_batch = X[batch_index]
    Y_batch = Y[batch_index]
    weights, bias = opt.step(cost, weights, bias, X=X_batch, Y=Y_batch)

    # Compute accuracy
    predictions = [np.sign(variational_classifier(weights, bias, x)) for x in X]

    current_cost = cost(weights, bias, X, Y)
    acc = accuracy(Y, predictions)

    print(f"Iter: {it+1:4d} | Cost: {current_cost:0.7f} | Accuracy: {acc:0.7f}")

Iter:    1 | Cost: 2.3147651 | Accuracy: 0.5000000
Iter:    2 | Cost: 1.9664866 | Accuracy: 0.5000000
Iter:    3 | Cost: 1.9208589 | Accuracy: 0.5000000
Iter:    4 | Cost: 2.6276126 | Accuracy: 0.5000000
Iter:    5 | Cost: 0.9323119 | Accuracy: 0.6000000
Iter:    6 | Cost: 1.1903549 | Accuracy: 0.5000000
Iter:    7 | Cost: 2.0508989 | Accuracy: 0.4000000
Iter:    8 | Cost: 1.1275531 | Accuracy: 0.6000000
Iter:    9 | Cost: 1.1659803 | Accuracy: 0.6000000
Iter:   10 | Cost: 1.1349618 | Accuracy: 0.6000000
Iter:   11 | Cost: 0.9994063 | Accuracy: 0.6000000
Iter:   12 | Cost: 1.0812559 | Accuracy: 0.6000000
Iter:   13 | Cost: 1.2863155 | Accuracy: 0.6000000
Iter:   14 | Cost: 2.2658259 | Accuracy: 0.4000000
Iter:   15 | Cost: 1.1323724 | Accuracy: 0.6000000
Iter:   16 | Cost: 1.3439737 | Accuracy: 0.8000000
Iter:   17 | Cost: 2.0076168 | Accuracy: 0.6000000
Iter:   18 | Cost: 1.2685760 | Accuracy: 0.5000000
Iter:   19 | Cost: 1.6762475 | Accuracy: 0.5000000
Iter:   20 | Cost: 1.1868237 | 

Lastly, we validate the trained model on test data. Sometimes models can overfit on the training data, and thus perform weakly over unseen data points. Thus, validation over test data is an important part of any ML (classical and quantum) pipeline.

In [14]:
data = np.loadtxt("variational_classifier/data/parity_test.txt", dtype=int)
X_test = np.array(data[:, :-1])
Y_test = np.array(data[:, -1])
Y_test = Y_test * 2 - 1  # shift label from {0, 1} to {-1, 1}

predictions_test = [np.sign(variational_classifier(weights, bias, x)) for x in X_test]

for x,y,p in zip(X_test, Y_test, predictions_test):
    print(f"x = {x}, y = {y}, pred={p}")

acc_test = accuracy(Y_test, predictions_test)
print("Accuracy on unseen data:", acc_test)

x = [0 0 0 0], y = -1, pred=-1.0
x = [0 0 1 1], y = -1, pred=-1.0
x = [1 0 1 0], y = -1, pred=-1.0
x = [1 1 1 0], y = 1, pred=1.0
x = [1 1 0 0], y = -1, pred=-1.0
x = [1 1 0 1], y = 1, pred=1.0
Accuracy on unseen data: 1.0
